[package]
name = "futures-channel-preview"
version = "0.2.2"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://github.com/rust-lang-nursery/futures-rs"
documentation = "https://docs.rs/futures-core"
description = """
Channels for asynchronous communication using futures-rs.
"""

[lib]
name = "futures_channel"

[features]
std = ["futures-core-preview/std"]
default = ["std"]

[dependencies]
futures-core-preview = { path = "../futures-core", version = "0.2.2", default-features = false }

[dev-dependencies]
futures-preview = { path = "../futures", version = "0.2.2", default-features = true }
futures-executor-preview = { path = "../futures-executor", version = "0.2.2", default-features = true }
