[workspace]
members = [
  "futures",
  "futures-core",
  "futures-channel",
  "futures-executor",
  "futures-io",
  "futures-select-macro",
  "futures-sink",
  "futures-util",
  "futures-test",
]

[patch.crates-io]
pin-project = { git = "https://github.com/taiki-e/pin-project", branch = "pin_project" }
