[package]
name = "futures-test-preview"
edition = "2018"
version = "0.3.0-alpha.19"
authors = ["Wim Looman <wim@nemo157.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://rust-lang-nursery.github.io/futures-rs"
documentation = "https://docs.rs/futures-test-preview/0.3.0-alpha.19"
description = """
Common utilities for testing components built off futures-rs.
"""

[lib]
name = "futures_test"

[dependencies]
futures-core-preview = { version = "=0.3.0-alpha.19", path = "../futures-core", default-features = false }
futures-task-preview = { version = "=0.3.0-alpha.19", path = "../futures-task", default-features = false }
futures-io-preview = { version = "=0.3.0-alpha.19", path = "../futures-io", default-features = false }
futures-util-preview = { version = "=0.3.0-alpha.19", path = "../futures-util", default-features = false }
futures-executor-preview = { version = "=0.3.0-alpha.19", path = "../futures-executor", default-features = false }
pin-utils = { version = "0.1.0-alpha.4", default-features = false }

[dev-dependencies]
futures-preview = { version = "=0.3.0-alpha.19", path = "../futures", default-features = false, features = ["std"] }

[features]
default = ["std"]
std = ["futures-core-preview/std", "futures-task-preview/std", "futures-io-preview/std", "futures-util-preview/std", "futures-util-preview/io", "futures-executor-preview/std"]
