[package]
name = "futures-util-preview"
edition = "2018"
version = "0.3.0-alpha.18"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://rust-lang-nursery.github.io/futures-rs"
documentation = "https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.18/futures_util"
description = """
Common utilities and extension traits for the futures-rs library.
"""

[lib]
name = "futures_util"

[features]
default = ["std"]
std = ["alloc", "futures-core-preview/std", "slab"]
alloc = ["futures-core-preview/alloc"]
async-await = ["std"]
compat = ["std", "futures_01"]
io-compat = ["io", "compat", "tokio-io"]
bench = []
nightly = ["futures-core-preview/nightly"]
cfg-target-has-atomic = ["futures-core-preview/cfg-target-has-atomic"]
sink = ["futures-sink-preview"]
io = ["std", "futures-io-preview", "memchr"]
channel = ["std", "futures-channel-preview"]
join-macro = ["async-await", "futures-join-macro-preview", "proc-macro-hack", "proc-macro-nested"]
select-macro = ["async-await", "futures-select-macro-preview", "proc-macro-hack", "proc-macro-nested", "rand"]

# re-export optional WASM dependencies to avoid breakage in getrandom:
wasm-bindgen = ["rand/wasm-bindgen"]
stdweb = ["rand/stdweb"]

[dependencies]
futures-core-preview = { path = "../futures-core", version = "=0.3.0-alpha.18", default-features = false }
futures-channel-preview = { path = "../futures-channel", version = "=0.3.0-alpha.18", default-features = false, features = ["std"], optional = true }
futures-io-preview = { path = "../futures-io", version = "=0.3.0-alpha.18", default-features = false, features = ["std"], optional = true }
futures-sink-preview = { path = "../futures-sink", version = "=0.3.0-alpha.18", default-features = false, optional = true }
futures-join-macro-preview = { path = "../futures-join-macro", version = "=0.3.0-alpha.18", default-features = false, optional = true }
futures-select-macro-preview = { path = "../futures-select-macro", version = "=0.3.0-alpha.18", default-features = false, optional = true }
proc-macro-hack = { version = "0.5.9", optional = true }
proc-macro-nested = { version = "0.1.2", optional = true }
rand = { version = "0.7.0", optional = true }
slab = { version = "0.4", optional = true }
memchr = { version = "2.2", optional = true }
futures_01 = { version = "0.1.25", optional = true, package = "futures" }
tokio-io = { version = "0.1.9", optional = true }
pin-utils = "0.1.0-alpha.4"

[dev-dependencies]
futures-preview = { path = "../futures", version = "=0.3.0-alpha.18", features = ["async-await", "nightly"] }
futures-test-preview = { path = "../futures-test", version = "=0.3.0-alpha.18" }
tokio = "0.1.11"

[package.metadata.docs.rs]
all-features = true
