[package]
name = "futures-core"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/futures-rs"
homepage = "https://github.com/alexcrichton/futures-rs"
documentation = "https://docs.rs/futures-core"
description = """
The core traits and types in for the `futures` library.
"""

[dependencies]
pin-api = { version = "0.1.2", default-features = false }

[features]
default = ["std"]
std = ["pin-api/std"]
nightly = ["pin-api/nightly"]
