[package]
name = "futuremio"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
mio = { git = "https://github.com/alexcrichton/mio", branch = "tcp-sync" }
# mio = "0.5"
futures = { path = ".." }
fnv = "1.0.2"

[lib]
test = false
