[package]
name = "futures-task"
edition = "2018"
version = "0.3.8"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/futures-rs"
homepage = "https://rust-lang.github.io/futures-rs"
documentation = "https://docs.rs/futures-task/0.3.8"
description = """
Tools for working with tasks.
"""

[features]
default = ["std"]
std = ["alloc", "once_cell"]
alloc = []

# These features are no longer used.
# TODO: remove in the next major version.
unstable = []
cfg-target-has-atomic = []

[build-dependencies]
autocfg = "1"

[dependencies]
once_cell = { version = "1.3.1", default-features = false, features = ["std"], optional = true }

[dev-dependencies]
futures = { path = "../futures", version = "0.3.8" }

[package.metadata.docs.rs]
all-features = true
