[package]
name = "futures-sink-preview"
edition = "2018"
version = "0.3.0-alpha.14"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://rust-lang-nursery.github.io/futures-rs"
documentation = "https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.14/futures_sink"
description = """
The asynchronous `Sink` trait for the futures-rs library.
"""

[lib]
name = "futures_sink"

[features]
std = ["alloc", "futures-core-preview/std", "futures-channel-preview/std"]
default = ["std"]
nightly = ["futures-core-preview/nightly"]
alloc = ["futures-core-preview/alloc"]

[dependencies]
futures-core-preview = { path = "../futures-core", version = "=0.3.0-alpha.14", default-features = false }
futures-channel-preview = { path = "../futures-channel", version = "=0.3.0-alpha.14", default-features = false }
